---
driver:
  name: docker
  use_sudo: false


platforms:
  - name: centos-7
  - name: fedora-26
  - name: debian-9
    provisioner:
      require_ansible_repo: false
      require_pip: true
  - name: debian-8
    provisioner:
      require_ansible_repo: false
      require_pip: true


provisioner:
  name: ansible_playbook
  require_ansible_repo: true
  require_ansible_omnibus: false
  ansible_version: 'latest'

  ansible_verbose: true
  require_chef_for_busser: false

  playbook: 'tests/test.yml'
  hosts: localhost


verifier:
  name: serverspec
  use_sudo: false
  #sudo_path: true

suites:
  - name: default
