---
- name: Install APT HTTPS transport
  package:
    name: 'apt-transport-https'
    state: present

- name: Import repo key
  apt_key:
    keyserver: 'keyserver.ubuntu.com'
    id: 'ABF5BD827BD9BF62'

- name: Configuring NGINX official repo
  apt_repository:
    filename: nginx
    repo: 'deb https://nginx.org/packages/debian/ {{ ansible_distribution_release }} nginx'
    state: present
    update_cache: yes
