---
# TODO(stefano): Use include_tasks as soon as possible.
#  - include_tasks is new in 2.4 and not all platforms have it.
- name: 'Configure upstream repo for supported platforms'
  include: '{{ item }}'
  with_first_found:
    - files:
        - 'tasks/{{ ansible_distribution }}/{{ ansible_distribution_major_version }}.yml'
        - 'tasks/{{ ansible_distribution }}.yml'
        - 'tasks/default.yml'


- name: Install NGINX package
  package:
    name: '{{ upstream_nginx_package }}'
    state: present


- name: Configure NGINX service
  service:
    name: '{{ upstream_nginx_service }}'
    enabled: '{{ upstream_nginx_service_enabled }}'
    state: '{{ upstream_nginx_service_state }}'
  when: upstream_nginx_service_manage
